-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Dec 30, 2022 at 06:35 PM
-- Server version: 10.4.22-MariaDB
-- PHP Version: 8.1.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `learning`
--

-- --------------------------------------------------------

--
-- Table structure for table `courses`
--

CREATE TABLE `courses` (
  `id` int(11) NOT NULL,
  `Course Code` varchar(30) NOT NULL,
  `Course Title` varchar(80) NOT NULL,
  `level` varchar(10) NOT NULL,
  `materials` varchar(2000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `courses`
--

INSERT INTO `courses` (`id`, `Course Code`, `Course Title`, `level`, `materials`) VALUES
(1, 'BIO 101', 'BASIC PRINCIPLES OF BIOLOGY', '100 Level', 'Levels of Biological Organisation: Basic characteristics of living things, Viral Exceptions; Microscope concepts; Macromolecules, Carbohydrates, Lipid, Proteins, and Nucleic Acids. Cell structures and functions of organelles. Basic principles of reproduction, mitosis and meiosis, growth; gametogenesis; inheritance and variation. Evolutionary trends.'),
(2, 'CHM 101', 'GENERAL CHEMISTRY 1', '100 Level', 'Atomic structure and the periodic classification of the elements; ionic and covalent bonding including the effect of dipole-dipole interacting on physical properties. Redox reactions and the concept of oxidation numbers; introduction to gas kinetics, introduction to nuclear chemistry. Solids and lattics structure; acide-base reactions; general principles of extraction of metals.'),
(3, 'GNS 101', 'USE OF LIBRARY', '100 Level', 'Libraries: Types and special services, the University Library. Library and Research Activities'),
(4, 'GNS 102', 'USE OF ENGLISH', '100 Level', 'The word, the clause and the sentence. Word classes: Verb, Nouns, Adjectives. Determiners, prepositions and conjunctions. Reading and comprehension. Summary writing. Note taking and Note making'),
(5, 'GNS 201', 'LAGOS AND IT\'S ENVIRONMENTS', '200 Level', 'Lagos is the largest city in Nigeria and one of the most populous cities in Africa. Located on the western coast of the country, Lagos is known for its bustling streets, vibrant culture, and diverse population.\r\n\r\nThe environment of Lagos is characterized by its tropical climate, with hot and humid weather year-round. The city is located on a coastal plain, which is subject to frequent flooding due to its low elevation. Lagos is also prone to tropical storms and hurricanes, which can cause significant damage to the city\'s infrastructure. agos is also a hub for arts and culture, with a vibrant music and film scene. The city is home to a number of museums, galleries, and cultural institutions, as well as a number of festivals and events throughout the year.'),
(6, 'ENT 202', 'BASIC PRINCIPLES OF ENTREPRENEURSHIP', '200 Level', 'Entrepreneurship is the process of starting and running a business, including identifying a product or service, analyzing the market, and managing resources. It involves taking risks, being innovative, and constantly seeking opportunities for growth and success. Successful entrepreneurship requires strong leadership, strategic planning, and the ability to adapt to changing market conditions. It also involves being able to identify and solve problems, and having a strong network of contacts and resources.'),
(7, 'GNS 301', 'LOGIC AND PHYLOSOPHY', '300 Level', 'Logic is a branch of philosophy that deals with the principles and methods of reasoning and argumentation. It is concerned with the logical structure of statements and arguments, and how they can be used to support or refute claims. Logic is used in many fields, including mathematics, computer science, and philosophy, to analyze and evaluate the validity and soundness of arguments.\r\n\r\nPhilosophy, on the other hand, is a discipline that deals with fundamental questions about reality, existence, knowledge, values, reason, and language. It encompasses a wide range of areas, including metaphysics, epistemology, ethics, politics, and aesthetics. Philosophy seeks to understand the nature of reality and the place of humans within it, as well as to provide answers to questions about the meaning and purpose of life.'),
(8, 'ENT 302', 'ENTREPRENEURSHIP II', '300 Level', 'Entrepreneurship is the process of starting and running a business, typically involving taking on financial risks in the hope of profit. It involves identifying a business opportunity, evaluating it, and then developing and marketing a product or service to meet the needs of the target market. Entrepreneurs often have a strong vision for their business and are willing to work hard and take risks to turn their ideas into reality. They also need to be able to adapt and be flexible in order to overcome challenges and setbacks. Successful entrepreneurship requires a combination of vision, perseverance, and practical skills such as financial management, marketing, and leadership.'),
(9, 'MAT 101', 'ALGEBRA', '100 Level', 'Real number system, principle of Mathematical induction, theory of quadratic equations, inequalities and partial fractions, series, AP, GP, Taylor\'s and Maclaurin\'s series. The Binomial theorem, set theory, set law, equivalence relations. Set functions and inverse set functions; polynomials. The remainder and factor theorems. Polynomial equations and inequalities (especially linear, quadratic and cubic). Domain and zeros of Rational functions; curve sketching of polynomials and rational functions. n root of unity. Introduction to algebra of m x n and square matrices. Properties of determinants.'),
(10, 'MAT 251', 'MATHEMATICAL METHODS I', '200 Level', 'Techniques of integration, reduction formula lebnitz theorem. PDE application to classification of critical system, points of functions of two variable coordinates, linear independence, Wronskian. Partial and total derivatives. Evaluation of lines, surface and volume integrals. Stoke\'s theorem. Solar and vector potential. Laplace\'s and poison\'s equations.'),
(11, 'PHY 101', 'GENERAL PHYSICS I', '100 Level', 'Dimensions, vectors; Newton\'s law of motion. 2-D motion: motion on a plane surface, circular motions. Orbital motion. Simple Harmonic Motion (of simple systems). Gravitation; moment of inertia; rotation of rigid bodies. Friction; viscosity; elasticity. Surface tension and capillarity effect; elements of fluid mechanics.'),
(12, 'PHY 103', 'BASIC HEAT', '100 Level', 'Heat, work and energy, temperature and thermal equilibrium: zeroth law of thermodynamics. Specific heat of solids, liquids and gases. Latent Heats. Gas laws: ideal and real gases. 1st law of thermodynamics: Isothermal, isobaric, isochoric and adiabatic processes. 2nd law of thermodynamics and its application. Heat transfer. Energy spectrum.'),
(13, 'PHY 105', 'EXPERIMENTAL PHYSICS I', '100 Level', 'Experiments arising from the theory courses of PHY 101 and PHY 103'),
(14, 'CSC 111', 'INTRODUCTION TO COMPUTER SCIENCE', '100 Level', 'Meaning and history of Computer Science. Generations of computers. Computer Hardware: functional components, Modern input and output units. Computer Software: Operating Systems, Application Packages. Program Development tools: Flow charts and algorithms. Programs Objects, BASIC or VISUAL BASIC Fundamentals.'),
(15, 'CSC 112', 'PRINCIPLES OF COMPUTER ORGANIZATION', '100 Level', 'Basic concepts of simple machine architecture, major components, functional relationship between the components of the processing UNITS (controls, memory and A.L.U) stored program concepts, representation of instruction in computer memory, addressing, instruction cycle. Computer design: organization, design operation and programming assemblers, program loaders and relocation. Levels of machine design; gates, register and processor levels. CPU design, instruction sets, von Neumann architecture, multiplication and division algorithms and implementation, floating point processors. Parallelism, multiprocessor etc. control unit design, hardwired and micro-programmed control. Memory design, hierarchical memory design, cache, associative and inter leaved memory.'),
(16, 'CSC 204', 'INTRODUCTION TO DISCRETE MATHEMATICS', '200 Level', 'Basic Set Theory: Basic definitions, Relations, Equivalence Relations Partition, Ordered Sets. Boolean Algebra & Lattices, Logic, Graph theory: Directed and Undirected graphs, Graph Isomorphism, Basic Graph Theorems, Matrices; Integer and Real matrices, Boolean Matrices, Matrices mod m, Path matrices. Adjacency Vectors/Matrices: Path adjacency matrix, Numerical & Boolean Adjacency matrices. Applications to counting, Discrete Probability Generating Functions,'),
(17, 'CSC 205', 'OPERATING SYSTEM 1', '200 Level', 'Introduction: Definition of Operating systems, history of Operating systems, Operating system structure-monolithic systems, layered systems, virtual machine, client server model processes: The process model, process state transitions, process control block, operation on processes, suspend and resume, Interrupt processing, nucleus, implementation of processes. inter-process communication; Race condition, critical section, mutual exclusion with busy waiting, sleep and wakeup, semaphores, event counters, monitor, message passing, equivalence of primitives, producer- consumer relationship, readers and writers problems, dining philosopher\'s problem, sleeping barber problem. Process Scheduling; scheduling objectives, scheduling criteria, preemptive vs. non-preemptive, interval timer or interrupting clock, deadline, FIFO, Round Robin, priorities, multiple queues, shortest job first, shortest remaining time, highest response ratio nest, fair share, policy versus mechanism, process management; '),
(18, 'CSC 208', 'INTRODUCTION TO HARDWARE LABORATORY', '200 Level', 'Identify and describe tools used for computer service and explain how to use those tools safely; Identify and describe the various internal components of a computer, assemble a computer system, install an operating system; Describe the purpose of preventive maintenance and basic troubleshooting steps; Troubleshoot using system tools and diagnostic software. Hands-on labs and interactive learning tools which help students to develop critical thinking and complex problem-solving skills; Identify and describe the main components of laptops and portable devices, basic preventive maintenance, and troubleshooting; Identify and describe the differences between printers and scanners, installation and configuration, basic preventive maintenance, and troubleshooting.'),
(19, 'CSC 213', 'ALGORITHM DEVELOPMENT AND APPLICATION', '200 Level', 'The study of algorithm design with emphasis on efficient algorithms and effective algorithms designs techniques and complexity, program design, string processing; recursion, NP completeness and approximating algorithms for NP Complete Problems. Algorithmic Strategies: Fundamental computing algorithms: Numerical algorithms, sequential and binary search algorithms; sorting algorithms, Binary Search tress, Hash tables, graphs & its representation, Greedy techniques, amortized analysis, approximation algorithms, cryptographic algorithms, distributed algorithms.'),
(20, 'CSC 214', 'DATABASE MANAGEMENT SYSTEM 1', '200 Level', 'Information in the organization, DBMS Technology and concepts, entity relational analysis, the relational data model, structured Query language (SQL), Functional dependency diagrams, Normalization of data, client server database technologies, Data Integrity. What is Data Modeling: Conceptual & physical models, instances, attributes and identifiers, Entity relationship modeling and ERDS, Entity Relationship Diagramming, Supertypes, Subtypes, and Business Rules, System development life cycle, Project overview and getting started, Presentation project management, Final presentation components, Presentation.'),
(21, 'CSC 215', 'SOFTWARE PRACTICE I', '200 Level', 'General introduction to programming. Structured programming elements, Structured Design principles, abstraction, modality, Stepwise refinement, structured design techniques. Teaching of a Structured Programming Language, Laboratory exercises in a Structured Programming Language. Focus on Visual Basic (VB) programming language. Data types. Events. GUI. IDE. Algorithm development, designing, coding, compilation, debugging and documentation. Real life application development. E.g. games, business, science and Engineering. Students should be encouraged to develop and present any application within their interest areas.'),
(22, 'CSC 217', 'FUNDAMENTALS OF DIGITAL ELECTRONICS', '200 Level', 'Voltage and current sources. kirchoff\'s laws, linearity and super-position. Therein Norton theorems, steady, state response to sinusoidal excitation; impulse response, semi-conductors, bipolar and field effect transistors; Logic circuit design (gates, multivibrators, etc.) using semi-conductors materials, integrated circuits, classification of IC circuits.'),
(23, 'CSC 218', 'FOUNDATION OF SEQUENTIAL PROGRAM', '200 Level', 'The relationships between H/L languages and the Computer Architecture that underlies their implementation: basic machine architecture, assemblers specification and translation of P/L Block Structured Languages, parameter passing mechanisms.'),
(24, 'CSC 221', 'FUNDAMENTALS OF DATA STRUCTURES', '200 Level', 'Elementary data items. Structured data item, array, ordered list, sparse matrices, stacks, queues sequences. Trees, simple sorting and searching techniques. Tree structures and graphs structures; polish notation, storage management and garbage collection. Hash coding, recursive programming, use of macros.'),
(25, 'CSC 222', 'ASSEMBLY PROGRAMMING LANGUAGE', '200 Level', 'Binary number systems and other systems. Types of encoding, modes of representations of data e.g. integer, floating, package decimal, character etc. Basic structure of the computer. Instruction set and corresponding machine language modes of addressing. Instruction execution and flow of macros, linkages, interfacing, assembling a language program with programs in the other languages, necessary aspect of job control languages.'),
(26, 'CSC 223', 'INTRODUCTION TO INFORMATION PROCESSING METHODS', '200 Level', 'Information systems, management information system, other information retrieval. Overview of file organization, data structure, sorting and merging, construction and maintenance of search trees. Decision tables, structure of decision tables.\r\n'),
(27, 'CSC 226', 'OBJECT ORIENTED PROGRAMMING I (C++)', '200 Level', 'Introduction to C: Structured Programming elements, structured design principles, abstraction modularity, stepwise refinement, structured design techniques. Teaching of a structured programming language such as C. Basic object-oriented Programming concepts, objects, inheritance, polymorphism, data abstraction, tools for developing, compiling, interrupting and debugging an object-oriented programming language. Laboratory exercises in an object-oriented programming language. C++'),
(28, 'CSC 303', 'OBJECT ORIENTED PROGRAMMING II (JAVA)', '300 Level', 'The focus of the course is on Java. Basic OOP Concepts: Classes, Objects, inheritance, polymorphism, Data Abstraction, Tools for developing, Compiling, interpreting and debugging, Java Programs, Java Syntax and data objects, operators. Central flow constructs, objects and classes programming, Arrays, methods. Exceptions, Applets and the Abstract, OLE, Persistence, Window or Unix Toolkit, Laboratory exercises in an OOP Language.'),
(29, 'CSC 319', 'COMPILER CONSTRUCTION', '300 Level', 'Review of compilers assemblers and interpreters, structure and functional aspects of a typical compiler, syntax semantics and pragatics, functional relationship between lexical analysis, expression analysis and code generation. Internal form of course programme. Use of a standard compiler (FORTRAN). Grammars and languages, recognizers, Top-down and bottom-up language Run-time storage Organization, The use of display in run-time storage Organization. The use of display in run time storage allocation. LR grammars and analysers. Construction of LR table. Organisation of symbol tablets. Allocation of storage to run-time variables. Code generation. Optimisation/Translator with systems.'),
(30, 'CSC 323', 'EVOLUTIONARY COMPUTATION', '300 Level', 'Introduction to Evolutionary Computation. Genetic Representation, search operators, selection schemes and selection pressure. Fitness Landscapes e.g. Configuration spaces, Properties of landscapes. Local optima; Basins. Multi-population methods. Co-evolution. Niching and Speciation. Multi- objective Evolutionary Optimisation. Dynamic optimisation Genetic Programming. A case study of Evolutionary methods. Evolving learning- machines, e.g. Neural Networks or Learning Classifier Systems.'),
(31, 'CSC 327', 'DATABASE MANAGEMENT SYSTEM 2', '300 Level', 'Rational Databases: Mapping conceptual schema to relational Schema; Database Query Languages (SQL) Concept of Functional dependencies & Multi Valued dependencies. Transaction processing; Distributed databases. Third normal form, Arcs, Hierarchies, and Historical Data, ERD Project Presentation, Drawing Conventions and Generic Modeling, Transforming from Conceptual Model to Physical Model.'),
(32, 'CSC 325', 'OPERATING SYSTEM 2', '300 Level', 'File System: Naming, Structure, Types, Access, Attributes, Operating Memory-mapped. Directories: Hierarchical part names, operations, implementation, shared files, disk space management, file system reliability, file system performance. File security: environment, security flaws, internet worms, security attacks, design principles in security, user authentication. Protection mechanisms: protection domain, Access control lists, capabilities, protection model, covert channels. Input/output: I/O devices, Device controllers, Direct Memory Access, Goals of I/O software, Interrupt handlers, Device drivers, Device Independent I/O software, User- Space I/O software, Disks Hardware, Disk arm scheduling algorithms, error handling, Track-at-a-Time caching, Ram disks, clocks: Clock Hardware, clock software. Terminal: Hardware, Memory-Mapped Terminals, Input software, output software. Case study: UNIX, OS/2, MSDOS and Open systems. A study of concurrency and writing concurrent programs, emphasis will be on language constructs used to express and control concurrency. Concurrent programming techniques an styles. Co-writers, mutual exclusion, semaphones, deadlock, high level concurrency, writer process communication and process structuring, laboratory exercises using a basic concurrent programs.'),
(33, 'CSC 333', 'COMPUTER RESEARCH METHODOLOGY', '300 Level', 'The meaning and concept of research. Types of research: Quantitative and qualitative. The Information skills: retrieving and recording bibliographic information from manual and computerized sources. Citation. Intellectual property rights; time management; report writing; oral presentation, plagiarism. Scientific writing.'),
(34, 'CSC 335', 'INTRODUCTION TO FORMAL LANGUAGE AND AUTOMATA THEORY', '300 Level', 'Formal Language: formal grammars, \'parsing, regular languages, context- free languages, automata theory. Finite state automata push-down automata. Compiler Construction: Grammars and language, recognizers, top-down and bottom-up production language; run-time. Storage organization. The use of display in run time storage allocation. LR grammars and analyzers of symbol tables. Allocation of storage to run time variable codes generation. Optimization translator writing systems.'),
(35, 'CSC 339', 'SYSTEMS ANALYSIS AND DESIGN', '300 Level', 'System Concept; System Development Life Cycle Analysis: Fact gathering Techniques, data flow diagrams, Process description data modeling. System Design: Structure Charts, form designs, security, automated Tools for design. Scope of systems analysis. System investigation. Input design output design. Review of design and organization of files. Design and documentation. Program designs, feasibility study. Systems analysis techniques, management information system, systems implementation and conversion.'),
(36, 'CSC 405', 'SOCIAL AND PROFESSIONAL ISSUES IN INFORMATION TECHNOLOGY', '400 Level', 'Ethical issues in the work place, in work-teams and with clients moral values generation, culture, heritage and technology im0plications of technology, globally and in Nigeria. Computer abuse, crime detection, legal issues in the IT profession community, global and environmental responsibility professional ethical codes personal responsibility.'),
(37, 'CSC 411', 'ORGANIZATION OF PROGRAMMING LANGUAGES', '400 Level', 'Programming languages are the foundation of modern computing. They provide the instructions that computers follow to perform tasks, and are essential for everything from simple calculations to complex software applications.'),
(38, 'CSC 413', 'SOFTWARE ENGINEERING', '400 Level', 'Introduction, Software process, Project planning, Requirement Engineering, System Models: Process Models; DFDS, State-transition, State charts UML, Data Models, ER Models, Object oriented modeling using UML, Software verification and validation, Software Testing. Topics from process improvement; Software re-engineering configuration management; formal specification, software cost- estimation, software Architecture, software patterns, software reuse and open source development.'),
(39, 'CSC 420', 'INTRODUCTION TO COMPUTER SECURITY', '400 Level', 'Private and public-key cryptography; block ciphers, data encryption, authentication, key distribution and certification, pseudorandom number generators, design and analysis of protocols, zero-knowledge proofs, and advanced protocols. Emphasizes rigorous mathematical approach including formal definitions of security goals and proofs of protocol security. Basic cryptography, security/threat analysis, access control, auditing, security models, distributed systems security, and theory behind common attack and defense techniques. The class will go over formal models as well as the bits and bytes of security exploits.'),
(40, 'CSC 424', 'EXPERT SYSTEMS AND KNOWLEDGE ENGINEERING', '400 Level', 'Introduction: The history of knowledge-based expert systems; Characteristics of current expert systems; and Basic concepts for building expert systems. Building and Expert System: The architecture of expert systems; Constructing an expert system; and Tools for building expert systems. Evaluating an Expert System: Reasoning about reasoning; and Issues and case studies. Language and Tools for Knowledge Engineering. A Case Study in Knowledge Engineering.'),
(41, 'CSC 428', 'COMPUTER GRAPHICS AND VISUAL COMPUTING', '400 Level', 'Hardware aspect: Plotters microfilm, display, graphic tables, light pens, other graphical input aids, facsimile and its problems. Refresh/display, refresh buggers, charging images light-pen interaction. Two and three dimensional transformations, perspective, chipping algorithms. Amode\'s method, shading, data reduction for graphical input, introduction of character recognition. Curve synthesis and fitting. Controlling, wing, structures, versus doubly linked bits hierarchical data structures, organization for interactive graphics.'),
(42, 'CSC 432', 'PRINCIPLES OF PROGRAMMING LANGUAGES', '400 Level', 'The effects of scale on programming methodology; Language Description: Syntactic Structure (Expression notations, abstract Syntax Tree, Lexical Syntax, Grammars for Expressions, Variants of Grammars), Language Semantics (Informal semantics, Overview of formal semantics, Denotation semantics, Axiomatic semantics, Operational semantics); Declarations and types: The concept of types, Declaration models (binding, visibility, scope, and lifetime), Overview of type-checking, Garbage collection; Abstraction mechanisms: Procedures, function, and iterations as abstraction mechanisms, Parameterization mechanisms (reference vs. value), Activation records and storage management, Type parameters and parameterized types, Modules in programming languages; Object oriented language paradigm; Functional and logic language paradigms.'),
(43, 'CSC 438', 'COMPUTER NETWORK AND DATA COMMUNICATION', '400 Level', 'Introduction to concepts, principles and practice of computer communication networks with examples from existing architectures, protocols, and standards. Layering and the OSL model, switching, local, metropolitan, and wide area networks, data grams and virtual circuits, mounting and congestion control, internet working. Introduction, wares, Fourier analysis, measure of communication, channel characteristics, transmission media, noise and distortion, modulation and demodulation, multiplexing, TDM FDM and FCM Parallel and serial transmission (synchronous Vs asynchronous). Bus structures and loop systems, computer network Examples and design consideration, data switching principles broadcast techniques, network structure for packet switching, protocols, description of network e.g. ARPANET, etc.'),
(44, 'CSC 426', 'FURTHER STATISTICAL PROCESSING', '400 Level', 'Topics to include: Multiple Regression Analysis; One-way Analysis Variance. Two-way Analysis of Variance; Generalized inverses and Applications; Statistical Control; use of Packages to solve Statistical problems.'),
(45, 'CSC 427', 'INTRODUCTION TO NUMERICAL COMPUTING', '400 Level', 'Numerical Data representation on computer, Computer as a crunching tool, Floating Point number, representation and arithmetic: Error, Stability, Convergence. Theory of computational solution to problem: numerical algorithm formulation and design, numeric software systems. Introduction to use of MATLAB and Maple in numerical computation and engineering applications. Emphasis is on the use of software to solve real problems. Iterative solution of non-linear systems (Newton\'s method) Numerical solution of linear systems. Numerical computation of Eigenvalues eigenvectors. Curve fitting; Function approximation. Numerical differentiation and integration (Simpson\'s rule, etc). Explicit and Implicit methods. Differential equations (Euler\'s Method, etc). Linear Algebra: Finite Differences. High performance computation.'),
(46, 'CSC 437', 'ARTIFICIAL INTELLIGENCE', '400 Level', 'Introduction to Artificial Intelligence, understanding natural languages, knowledge representation, export system pattern recognition, the language HLSP and PROLOG. Intelligent agents; Problem solving as search: Search strategies: Breath first, Depth-first, uniform cost, dept constraint satisfaction Problems, Backtracking search for CSP, Constraint Propagation, Local search for CSPs. Logic-based knowledge representation.'),
(47, 'CSC 451', 'HUMAN COMPUTER INTERFACE', '400 Level', 'Foundations of HCI, Principles of GUI, GUI toolkits; Human-centred software evaluation and development; GUI design and programming.'),
(48, 'CSC 429', 'MODELING AND SIMULATION', '400 Level', 'The concepts and techniques used in modeling and simulation methodology and a suitable simulation language (SIMPSCRIPT, etc.), inventory control product scheduling, quality control, industrial simulation and forecast, modeling generation of random variables.'),
(49, 'CSC 454', 'DIGITAL IMAGE PROCESSING', '400 Level', 'Digitization and coding of images, characterization and representation of digital images in spatial and frequency domains, image restoration, perception and enhancement, point-, algebraic-, and geometric operations, discrete image transforms, image filtering, image reconstruction, pattern recognition principles: segmentation and object measurement.'),
(50, 'CSC 452', 'ROBOTICS', '400 Level', 'Mathematical modeling of robot mechanisms and the analysis methods used to design control laws for these mechanisms. Homogeneous transformations and relative coordinate frames. Topics include: kinematics of robot manipulators, Robot velocities and static forces, manipulator dynamics, reference trajectory generation, control theory applied to robot manipulators, and tele-operation control.'),
(51, 'CSC 442', 'INTRODUCTION TO PHP & MYSQL', '400 Level', 'Meaning of a Web Database Application. The database, the application: Moving data in and out of the database, MYSQL, Communicating with the MYSQL How MYSQL works, Advantages of PHP, How PHP works, MYSQL and PHP, the Perfect Pair, Advantages of the relationship, How MYSQL and PHP work together, keeping Up with PHP and MYSQL Changes,'),
(52, 'CSC 392', 'PRACTICAL APPLICATION OF SOFTWARE DEVELOPMENT IN INDUSTRIES', '300 Level', 'The main aim of this course is to give students the opportunity to develop a software package of choice. Students are required to use the software principles learnt so far to develop at least one software package related to the industry where they are undergoing SIWES. The software should reflect the understanding of System Development Life Cycle. Any programming language could be used, e.g. java, C++, etc. Students should also demonstrate ability to create and interrogate databases and their components. Each student is required to submit a CD/DVD containing the source code and the binary or compiled version of the software package at the end of SIWES to the department for assessment. The CD should also contain the documentation on how to use the software, system requirements and installation instruction.'),
(53, 'CSC 394', 'PRACTICAL APPLICATION OF DATABASE MANAGEMENT IN INDUSTRIES\r\n\r\n', '300 Level', 'Record keeping is very important in business management and every company or business keeps record and accesses such records at one point or the order. A major challenge in record management is the manual approach of record keeping which is commonly used in Nigeria. Computer Scientists attempt to solve this problem by automating record keeping using database management system concepts. The aim of this course is to encourage each student to apply the concepts of database management learnt in the class to the company where SIWES is undertaken. Students are required to create databases using any package of choice, e.g. MySQL, PostgreSQL, Microsoft SQL, MS-Access, Oracle, Sybase, Ingress, Informix, etc. They are also required to demonstrate ability to manipulate tables, issue queries, generate/design reports and forms, link tables, etc. Students could also demonstrate front-end programming ability by using programming languages like PHP, VB.NET, Java, etc in managing the database created. Each student is required to submit a CD containing the package developed at the end of SIWES to the department for assessment. The CD should also contain the documentation on how to use the software, system requirements and installation instruction.'),
(54, 'CSC 396', 'PRACTICAL APPLICATION OF DATA AND INFORMATION PRESENTATION SKILLS', '300 Level', 'The most commonly used computer applications in offices are office packages and this is not covered by the university curriculum, though with the understanding that students could acquire the skills during their training. Unfortunately, this never happens and many BSc. Computer Science students leave the university without any knowledge of office applications. The aim of this course is to expose students to office applications, c.g. MS word Excel and powerpoint. Students are required to demonstrate ability to use MS word, Excel and powerpoint or equivalent open office applications. MS Word: Open a new documents, format documents, change fonts size and type, insert page numbers, italicise, boldface, conversion for pdf files, equations, creation of CV, header and footnotes, mail merge, tables, tracking changes, references and bibliography, etc. Excel: Create new spreadsheet, create records related, use formula, macros, format cells, merge cells, split cells, import text files, conversion of spreadsheet files to comma separated files, export as pdf files, etc. Powerpoint: Create slides and presentations, use different designs, and layouts, slide show, slide timing tool, printing, animations, inserting tables, figures, clip arts, slides rehearsing and recording, Document Workflow, Electronic Document Management System,Other Office Applications: Payroll, Pension Manager, Human Resources, Customer Relation Management/CRM), etc. Each student is required to submit an electronic copy in CD form of any document created using office tools listed above.'),
(55, 'CSC 398', 'STUDENTS\' INDUSTRIAL WORK EXPERIENCE SCHEME (SIWES)\r\n\r\n', '300 Level', 'The SIWES is a work based training programme for a period of six months, in the industry, under the follow up of an academic faculty member from the department of Computer Sciences, Lagos state university. SIWES gives students the opportunity to apply the knowledge acquired during the BSc. Programme to the industry and also to identify problems that could be solved using computational techniques. Students must get a formal/written approval from the head of department before proceeding on the training. Periodic reports and a final report must be submitted for evaluation, an oral examination is required. The first report shall be due for submission at the end of the first three weeks of SIWES. The first report which must be sent electronically to the head of department will contain the activities of the industry, how the industry uses Computer Science / information technology, and the roles assigned to the student. The final report shall contain a summative report of the roles of the students within the industry, what was learnt, challenges and recommendations. This course cannot be taken by students not studying for the award of BSc. in Computer Sciences.'),
(56, 'CSC 497', 'SEMINAR ON SPECIAL TOPICS IN COMPUTER SCIENCE', '400 Level', 'Students are required to choose topics on special topics in computer science under the guidance of a supervisor. Students are required to submit the bond form of the seminar to the department upon completion. Topics could include, but not limited to, any of the following: Performance Evaluation of Computer Systems, Concurrent Programming, Pattern Recognition, Distributed Database, Programming Environments, High-Level Language and Data flow Architectures, Computer Vision, Planning, Natural and Spoken Language Understanding, Temporal Logics, Supercomputing VLSI Design, Human Computer Interaction and so on.'),
(57, 'CSC 498', 'FINAL YEAR PROJECT', '400 Level', 'This is an independent project where students are required to carry out a research. A project topic to be chosen by each student under the guidance of the supervisor. Students are required to submit the bond form of the project to the department upon completion.');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `first name` varchar(30) NOT NULL,
  `last name` varchar(30) NOT NULL,
  `email` varchar(50) NOT NULL,
  `matricNo` varchar(9) NOT NULL,
  `faculty` varchar(100) NOT NULL,
  `department` varchar(100) NOT NULL,
  `level` varchar(10) NOT NULL,
  `password` varchar(200) NOT NULL,
  `mycourse` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `first name`, `last name`, `email`, `matricNo`, `faculty`, `department`, `level`, `password`, `mycourse`) VALUES
(1, 'Basit', 'Adelaja', 'sanniopeyemiolayinka@gmail.com', '', '', '', '', '1', ', csc221, csc111, csc112, csc303, csc333, csc325, csc339, csc405, csc413, csc497, csc221, csc223, csc226, chm101, CSC427'),
(3, 'opeyemi', 'Sanni', 'sanni1@gmail.com', '180591052', '05', '004', '400', '2', ', csc111');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `courses`
--
ALTER TABLE `courses`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `courses`
--
ALTER TABLE `courses`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=59;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=17;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
